// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as Types from "./Types.bs.js";
import * as Js_dict from "rescript/lib/es6/js_dict.js";

function loadPayglo(str, option) {
  return new Promise((function (resolve, reject) {
                var sessionID = Types.generateSessionID(undefined);
                var timeStamp = Date.now();
                var match = Types.getEnv(option);
                var scriptURL;
                switch (match) {
                  case "PROD" :
                  case "SANDBOX" :
                      scriptURL = "https://checkout.payglo.io/PaygloLoader.js";
                      break;
                  default:
                    str.startsWith("pk_prd_");
                    scriptURL = "https://checkout.payglo.io/PaygloLoader.js";
                }
                var analyticsObj = Js_dict.fromArray([
                      [
                        "sessionID",
                        sessionID
                      ],
                      [
                        "timeStamp",
                        String(timeStamp)
                      ]
                    ]);
                if (document.querySelectorAll("script[src=\"" + scriptURL + "\"]").length === 0) {
                  var script = document.createElement("script");
                  script.src = scriptURL;
                  script.onload = (function (param) {
                      var instance = window.Payglo;
                      if (!(instance == null)) {
                        return resolve(Curry._3(instance, str, option, analyticsObj));
                      }
                      
                    });
                  script.onerror = (function (err) {
                      reject(err);
                    });
                  document.body.appendChild(script);
                  return ;
                }
                console.warn("INTEGRATION WARNING: There is already an existing script tag for " + scriptURL + ". Multiple additions of PaygloLoader.js is not permitted, please add it on the top level only once.");
                var instance = window.Payglo;
                if (!(instance == null)) {
                  return resolve(Curry._3(instance, str, option, analyticsObj));
                }
                
              }));
}

function loadStripe(str, option) {
  console.warn("loadStripe is deprecated. Please use loadPayglo instead.");
  return loadPayglo(str, option);
}

export {
  loadPayglo ,
  loadStripe ,
}
/* Types Not a pure module */
